// Generated by https://quicktype.io

export type LoginResponse = {
    result: string;
    data: Data;
};

export type Data = {
    username: string;
    level: string;
    createdAt: string;
    updatedAt: string;
};
